baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Cruz Daniel Rubio Lucas."
    subtitle: "Game Programmer"
    # roundImage: true # Make hero image circular | default false


  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      I would like to create some moments who a lot of times we search in a game to have a good time and make people have curiosity on discover more about the game.
      
      I consider myself a committed person with my targets, I want to learn more and have a better knowledge to create good experiences in the future.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C"
        - "C++"
        - "C#"
        - "SDL"
        - "Unity"

  
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Licenciatura en Computación"
        school:
          name: "Universidad Autónoma Metropolitana unidad Iztapalapa"
        date: "2016-2021"

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Ms Pac Man
        content: Eat all pac dots to pass level, avoid ghosts or eat them when they are on frightened mode and get the most possible points through 4 different maps.
        image: /images/projects/pac2.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/MsPacMan
        badges:
          - "Unity"
          - "C#"

      - title: Gradius
        content: Survive alone or with a partner, destroy the enemies and boss, avoid enemy bullets and get upgrades like speed up, 2 bullets, shield, etc. You can change controls on the pause menu.
        image: /images/projects/gradGame.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/Gradius
        badges:
          - "Unity"
          - "C#"

      - title: Multiplayer
        content: Play on LAN with your friends, shoot them with different weapons, get life and speed by touching the boxes on the map, use the teleporters to reach new places and escape from other players.
        image: /images/projects/mul1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/Multiplayer
        badges:
          - "Unity"
          - "C#"
      - title: Asteroids
        content: Shoot bullets and destroy the asteroids, get money and buy new ships, bullets, asteroids, etc. You can use commands to get money, lifes or show FPS.
        image: /images/projects/ast.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/Asteroids
        badges:
          - "Unity"
          - "C#"
      - title: MN
        content: Avoid the enemies jumping, crouching or running, reach the last side of the map and pass the level.
        image: /images/projects/mn1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/MN
        badges:
          - "Unity"
          - "C#"
      - title: Pong
        content: Play alone or with a partner, make the ball enter in the goal of the other player to get points. You can change controls on the menu.
        image: /images/projects/pong1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/UnityGames/tree/main/Pong
        badges:
          - "Unity"
          - "C#"
      - title: Gradius
        content: Survive alone or with a partner, destroy the enemies and boss, avoid enemy bullets and get upgrades like speed up, 2 bullets, shield, etc.
        image: /images/projects/gradC1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/Games/tree/master/Gradius
        badges:
          - "C++"
          - "C"
      - title: Asteroids
        content: Shoot bullets and destroy the asteroids.
        image: /images/projects/astC1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/Games/tree/master/Asteroids
        badges:
          - "C++"
          - "C"
      - title: Breakout
        content: Hit the bricks with the ball, make them disappear and pass the level when all the bricks are destroyed. Get upgrades like extra ball and shoot bullets. You can use commands for different things and change volume from the pause menu.
        image: /images/projects/Breakout1.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/Games/tree/master/Breakout
        badges:
          - "C++"
          - "C"
      - title: Pong
        content: Play alone or with a partner, make the ball enter in the goal of the other player to get points.
        image: /images/projects/pongC.jpg
        featured:
          name: Code
          link: https://github.com/cruzdan/Games/tree/master/Pong
        badges:
          - "C++"
          - "C"
        

  #Contact
  contact:
    enable: true
    title: "Contact"
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/cruzdan
      linkedin: https://www.linkedin.com/in/cruzdanielrl/

